apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sample
    app.kubernetes.io/part-of: summer-beach-app
  name: python-sample
  namespace: rhn-support-tshearon
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: python-sample
status:
  loadBalancer: {}
